#!/usr/bin/env node

const byte = require("./index");
const readline = require("readline");
const fs = require("fs");

if (process.argv.length > 2) {
  fs.readFile(process.argv[2], function (err, buf) {
    console.log(byte.evaluate(byte.parse(buf.toString())).output);
    process.exit(0);
  });
} else {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  let state = null;
  rl.setPrompt("> ");
  rl.prompt();
  rl.on("line", function (data) {
    let out;

    if (data === ":q") {
      rl.close();
    }

    state = byte.evaluate(byte.parse(data), state);
    console.log(state.output === "" ? state.data.retval: state.output);
    state.output = "";
    rl.prompt();
  });
}
